name: Docker

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
  pull_request:
  release:
    types:
      - published
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build container image
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          repository: ${{ github.repository }}
          tag_with_ref: true
          add_git_labels: true
