name: Unix Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types:
      - published

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install clang-format
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 14
          rm llvm.sh
          sudo apt-get install -y --no-install-recommends clang-format-14

      - name: Format files
        run: find src include -type f -a \( -name "*.cc" -o -name "*.h" \) -print0 | xargs -0 clang-format-14 -i

      - name: Check for differences
        run: |
          git status --porcelain
          git status --porcelain | xargs -I {} -0 test -z \"{}\"

  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: macOS Release
            cxx: clang++
            cc: clang
            mode: Release
            mimalloc: off
            cxxflags: -stdlib=libc++
            os: macos-latest
            artifact: macos
          - name: GCC 10 Release
            cxx: g++-10
            cc: gcc-10
            mode: Release
            mimalloc: on
            os: ubuntu-latest
            artifact: linux
          - name: GCC 10 Debug
            cxx: g++-10
            cc: gcc-10
            mode: Debug
            mimalloc: on
            os: ubuntu-latest
          - name: Clang 14 Release
            cxx: clang++-14
            cc: clang-14
            mode: Release
            mimalloc: on
            cxxflags: -stdlib=libc++
            ldflags: -lc++abi
            os: ubuntu-latest
          - name: Clang Tidy
            cxx: clang++-14
            cc: clang-14
            mode: Release
            mimalloc: off
            cxxflags: -stdlib=libc++
            ldflags: -lc++abi
            lint: true
            os: ubuntu-latest
          - key: Clang 14 Sanitizer
            cxx: clang++-14
            cc: clang-14
            mode: Release
            mimalloc: off
            cflags: -fsanitize=address,undefined -fno-omit-frame-pointer
            cxxflags: -fsanitize=address,undefined -fno-omit-frame-pointer -stdlib=libc++
            ldflags: -lc++abi
            os: ubuntu-latest
    env:
      BUILDCACHE_COMPRESS: true
      BUILDCACHE_DIRECT_MODE: true
      BUILDCACHE_ACCURACY: SLOPPY
      BUILDCACHE_LUA_PATH: ${{ github.workspace }}/tools
      BUILDCACHE_DIR: ${{ github.workspace }}/.buildcache
      UBSAN_OPTIONS: halt_on_error=1:abort_on_error=1
    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-ninja@master

      # ==== INSTALL ====
      - name: Upgrade Packages
        if: matrix.config.os != 'macos-latest'
        env:
          DEBIAN_FRONTEND: noninteractive
        run: sudo apt-get update

      - name: Install LLVM
        if: matrix.config.os != 'macos-latest' && matrix.config.cc == 'clang-14'
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 14
          rm llvm.sh
          sudo apt-get install -y --no-install-recommends libc++-14-dev libc++abi-14-dev clang-tidy-14 libclang-common-14-dev libclang-rt-14-dev

      - name: Install Valgrind
        if: matrix.config.mode == 'Debug' && matrix.config.cc == 'gcc-10'
        env:
          DEBIAN_FRONTEND: noninteractive
        run: sudo apt-get install -y --no-install-recommends valgrind

      # ==== CACHING ====
      - name: buildcache Cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.buildcache
          key: buildcache-${{ matrix.config.os }}-${{ matrix.config.cc }}-${{ matrix.config.mode }}-${{ contains(matrix.config.cxxflags, 'sanitize') }}-${{ matrix.config.lint }}-${{ hashFiles('.pkg') }}-${{ hashFiles('**/*.h') }}-${{ hashFiles('**/*.cc') }}
          restore-keys: |
            buildcache-${{ matrix.config.os }}-${{ matrix.config.cc }}-${{ matrix.config.mode }}-${{ contains(matrix.config.cxxflags, 'sanitize') }}-${{ matrix.config.lint }}-${{ hashFiles('.pkg') }}-${{ hashFiles('**/*.h') }}-
            buildcache-${{ matrix.config.os }}-${{ matrix.config.cc }}-${{ matrix.config.mode }}-${{ contains(matrix.config.cxxflags, 'sanitize') }}-${{ matrix.config.lint }}-${{ hashFiles('.pkg') }}-
            buildcache-${{ matrix.config.os }}-${{ matrix.config.cc }}-${{ matrix.config.mode }}-${{ contains(matrix.config.cxxflags, 'sanitize') }}-${{ matrix.config.lint }}-

      - name: Dependencies Cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/deps
          key: deps-${{ hashFiles('.pkg') }}
          restore-keys: deps-

      # ==== BUILD ====
      - name: CMake
        run: |
          cmake \
            -G Ninja -S . -B build \
            -DCMAKE_C_COMPILER=${{ matrix.config.cc }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }} \
            -DCMAKE_C_FLAGS="${{ matrix.config.cflags }}" \
            -DCMAKE_CXX_FLAGS="${{ matrix.config.cxxflags }}" \
            -DCMAKE_EXE_LINKER_FLAGS="${{ matrix.config.ldflags }}" \
            -DCMAKE_BUILD_TYPE=${{ matrix.config.mode }} \
            -DPPR_LINT=${{ matrix.config.lint }} \
            -DPPR_MIMALLOC=${{ matrix.config.mimalloc }}

      - name: Build
        run: |
          ./build/buildcache/bin/buildcache -z
          cmake --build build --target ppr-preprocess ppr-backend footrouting ppr-benchmark
          ./build/buildcache/bin/buildcache -s

      # ==== DISTRIBUTION ====
      - name: Strip Executables
        if: matrix.config.mode == 'Release' && (matrix.config.cc == 'gcc-10' || matrix.config.os == 'macos-latest')
        run: |
          strip build/ppr-preprocess
          strip build/ppr-backend
          strip build/footrouting

      - name: Create Distribution
        if: matrix.config.mode == 'Release' && (matrix.config.cc == 'gcc-10' || matrix.config.os == 'macos-latest')
        run: |
          mkdir ppr
          mv build/ppr-preprocess ppr
          mv build/ppr-backend ppr
          mv build/footrouting ppr
          mv ui/web ppr
          tar cjf ppr-${{ matrix.config.artifact }}.tar.bz2 ppr

      - name: Upload Distribution
        if: matrix.config.mode == 'Release' && (matrix.config.cc == 'gcc-10' || matrix.config.os == 'macos-latest')
        uses: actions/upload-artifact@v2
        with:
          name: ppr-${{ matrix.config.artifact }}
          path: ppr-${{ matrix.config.artifact }}.tar.bz2

      # ==== RELEASE ====
      - name: Upload Release
        if: github.event.action == 'published' && matrix.config.mode == 'Release' && (matrix.config.cc == 'gcc-10' || matrix.config.os == 'macos-latest')
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./ppr-${{ matrix.config.artifact }}.tar.bz2
          asset_name: ppr-${{ matrix.config.artifact }}.tar.bz2
          asset_content_type: application/x-tar
