name: Unix Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  formatting:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install clang-format
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get install -y --no-install-recommends \
            apt-transport-https \
            ca-certificates \
            software-properties-common
          wget -nv -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
          sudo add-apt-repository "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-16 main"
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            clang-format-16

      - name: Format files
        run: find src include -type f -a \( -name "*.cc" -o -name "*.h" \) -print0 | xargs -0 clang-format-16 -i

      - name: Check for differences
        run: |
          git status --porcelain
          git status --porcelain | xargs -I {} -0 test -z \"{}\"

  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: macOS Release
            cxx: clang++
            cc: clang
            mode: Release
            mimalloc: on
            cxxflags: -stdlib=libc++
            os: macos-latest
            artifact: macos
          - name: GCC 12 Release
            cxx: g++-12
            cc: gcc-12
            mode: Release
            mimalloc: on
            os: ubuntu-22.04
            artifact: linux
          - name: GCC 12 Debug
            cxx: g++-12
            cc: gcc-12
            mode: Debug
            mimalloc: on
            os: ubuntu-22.04
          - name: Clang 16 Release
            cxx: clang++-16
            cc: clang-16
            mode: Release
            mimalloc: on
            cxxflags: -stdlib=libc++
            ldflags: -lc++abi
            os: ubuntu-22.04
          - name: Clang Tidy
            cxx: clang++-16
            cc: clang-16
            mode: Release
            mimalloc: on
            cxxflags: -stdlib=libc++
            ldflags: -lc++abi
            lint: true
            os: ubuntu-22.04
          - key: Clang 16 Sanitizer
            cxx: clang++-16
            cc: clang-16
            mode: Release
            mimalloc: on
            cflags: -fsanitize=address,undefined -fno-omit-frame-pointer
            cxxflags: -fsanitize=address,undefined -fno-omit-frame-pointer -stdlib=libc++
            ldflags: -lc++abi
            os: ubuntu-22.04
    env:
      BUILDCACHE_COMPRESS: true
      BUILDCACHE_DIRECT_MODE: true
      BUILDCACHE_ACCURACY: SLOPPY
      BUILDCACHE_LUA_PATH: ${{ github.workspace }}/tools
      BUILDCACHE_DIR: ${{ github.workspace }}/.buildcache
      UBSAN_OPTIONS: halt_on_error=1:abort_on_error=1
      CLICOLOR_FORCE: 1
    steps:
      - uses: actions/checkout@v3

      # ==== INSTALL ====
      - name: Update Packages
        if: matrix.config.os != 'macos-latest'
        env:
          DEBIAN_FRONTEND: noninteractive
        run: sudo apt-get update

      - name: Install LLVM
        if: matrix.config.os != 'macos-latest' && matrix.config.cc == 'clang-16'
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get install -qq --no-install-recommends \
            apt-transport-https \
            ca-certificates \
            software-properties-common
          wget -nv -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
          sudo add-apt-repository "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-16 main"
          sudo apt-get update
          sudo apt-get purge --auto-remove \
            llvm \
            llvm-14 \
            python3-lldb-14 \
            libc++-dev \
            libc++1-14 \
            libc++abi-dev \
            libc++abi1-14 \
            libc++abi-14-dev \
            libunwind-14 \
            libunwind-14-dev
          sudo apt-get install -y --no-install-recommends \
            clang-16 \
            clang-tools-16 \
            clang-format-16 \
            clang-tidy-16 \
            libc++-16-dev \
            libc++abi-16-dev \
            libclang-common-16-dev \
            libclang-rt-16-dev \
            libunwind-16-dev

      - name: Install ninja (Ubuntu)
        if: matrix.config.os != 'macos-latest'
        env:
          DEBIAN_FRONTEND: noninteractive
        run: sudo apt-get install -y --no-install-recommends ninja-build

      - name: Install ninja (macOS)
        if: matrix.config.os == 'macos-latest'
        run: brew install ninja

      - name: Install Valgrind
        if: matrix.config.mode == 'Debug' && matrix.config.cc == 'gcc-12'
        env:
          DEBIAN_FRONTEND: noninteractive
        run: sudo apt-get install -y --no-install-recommends valgrind

      # ==== RESTORE CACHE ====
      - name: Restore buildcache Cache
        uses: actions/cache/restore@v3
        id: restore-buildcache
        with:
          path: ${{ github.workspace }}/.buildcache
          key: buildcache-${{ matrix.config.os }}-${{ matrix.config.cc }}-${{ matrix.config.mode }}-${{ contains(matrix.config.cxxflags, 'sanitize') }}-${{ matrix.config.lint }}-${{ hashFiles('.pkg') }}-${{ hashFiles('**/*.h') }}-${{ hashFiles('**/*.cc') }}
          restore-keys: |
            buildcache-${{ matrix.config.os }}-${{ matrix.config.cc }}-${{ matrix.config.mode }}-${{ contains(matrix.config.cxxflags, 'sanitize') }}-${{ matrix.config.lint }}-${{ hashFiles('.pkg') }}-${{ hashFiles('**/*.h') }}-
            buildcache-${{ matrix.config.os }}-${{ matrix.config.cc }}-${{ matrix.config.mode }}-${{ contains(matrix.config.cxxflags, 'sanitize') }}-${{ matrix.config.lint }}-${{ hashFiles('.pkg') }}-
            buildcache-${{ matrix.config.os }}-${{ matrix.config.cc }}-${{ matrix.config.mode }}-${{ contains(matrix.config.cxxflags, 'sanitize') }}-${{ matrix.config.lint }}-

      - name: Restore Dependencies Cache
        uses: actions/cache/restore@v3
        id: restore-deps-cache
        with:
          path: ${{ github.workspace }}/deps
          key: deps-${{ hashFiles('.pkg') }}
          restore-keys: deps-

      # ==== BUILD ====
      - name: CMake
        run: |
          cmake \
            -G Ninja -S . -B build \
            -DCMAKE_C_COMPILER=${{ matrix.config.cc }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }} \
            -DCMAKE_C_FLAGS="${{ matrix.config.cflags }}" \
            -DCMAKE_CXX_FLAGS="${{ matrix.config.cxxflags }}" \
            -DCMAKE_EXE_LINKER_FLAGS="${{ matrix.config.ldflags }}" \
            -DCMAKE_BUILD_TYPE=${{ matrix.config.mode }} \
            -DPPR_LINT=${{ matrix.config.lint }} \
            -DPPR_MIMALLOC=${{ matrix.config.mimalloc }}

      - name: Build
        run: |
          ./build/buildcache/bin/buildcache -z
          cmake --build build --target ppr-preprocess ppr-backend footrouting ppr-benchmark
          ./build/buildcache/bin/buildcache -s

      # ==== DISTRIBUTION ====
      - name: Strip Executables
        if: matrix.config.mode == 'Release' && (matrix.config.cc == 'gcc-12' || matrix.config.os == 'macos-latest')
        run: |
          strip build/ppr-preprocess
          strip build/ppr-backend
          strip build/footrouting

      - name: Create Distribution
        if: matrix.config.mode == 'Release' && (matrix.config.cc == 'gcc-12' || matrix.config.os == 'macos-latest')
        run: |
          mkdir ppr
          mv build/ppr-preprocess ppr
          mv build/ppr-backend ppr
          mv build/footrouting ppr
          mv ui/web ppr
          tar cjf ppr-${{ matrix.config.artifact }}.tar.bz2 ppr

      - name: Upload Distribution
        if: matrix.config.mode == 'Release' && (matrix.config.cc == 'gcc-12' || matrix.config.os == 'macos-latest')
        uses: actions/upload-artifact@v3
        with:
          name: ppr-${{ matrix.config.artifact }}
          path: ppr-${{ matrix.config.artifact }}.tar.bz2

      # ==== RELEASE ====
      - name: Upload Release
        if: github.event.action == 'published' && matrix.config.mode == 'Release' && (matrix.config.cc == 'gcc-12' || matrix.config.os == 'macos-latest')
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./ppr-${{ matrix.config.artifact }}.tar.bz2
          asset_name: ppr-${{ matrix.config.artifact }}.tar.bz2
          asset_content_type: application/x-tar

      # ==== SAVE CACHE ====
      - name: Save buildcache Cache
        if: always()
        uses: actions/cache/save@v3
        with:
          path: ${{ github.workspace }}/.buildcache
          key: ${{ steps.restore-buildcache.outputs.cache-primary-key }}

      - name: Save Dependencies Cache
        if: always()
        uses: actions/cache/save@v3
        with:
          path: ${{ github.workspace }}/deps
          key: ${{ steps.restore-deps-cache.outputs.cache-primary-key }}
